#!/usr/bin/env python3
"""
emailer.py - Email Notification Module for sipwise-backup
Handles SMTP email notifications for backup and reboot events
"""

import smtplib
import socket
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import Dict, Optional
from pathlib import Path
import yaml


class EmailNotifier:
    """Handles email notifications for sipwise-backup"""
    
    def __init__(self, config_path: str = "/opt/sipwise-backup/config.yml"):
        """
        Initialize the EmailNotifier
        
        Args:
            config_path: Path to the configuration file
        """
        self.config_path = config_path
        self.config = self._load_config()
        self.log_dir = Path("/opt/sipwise-backup/log")
    
    def _load_config(self) -> dict:
        """Load configuration from config.yml"""
        try:
            with open(self.config_path, 'r') as f:
                return yaml.safe_load(f) or {}
        except Exception:
            return {}
    
    def is_enabled(self) -> bool:
        """Check if email notifications are enabled"""
        email_config = self.config.get('email', {})
        return email_config.get('enabled', False)
    
    def should_notify(self, event_type: str) -> bool:
        """
        Check if notification should be sent for this event type
        
        Args:
            event_type: One of 'backup_success', 'backup_failure', 'reboot_success', 'reboot_failure'
        """
        if not self.is_enabled():
            return False
        
        notifications = self.config.get('email', {}).get('notifications', {})
        return notifications.get(event_type, False)
    
    def get_server_info(self) -> Dict[str, str]:
        """Get server name and IP address"""
        server_name = self.config.get('server_name', 'unknown-server')
        server_type = self.config.get('instance_type', 'unknown')
        
        # Get IPv4 address
        try:
            s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            s.connect(("8.8.8.8", 80))
            ip_address = s.getsockname()[0]
            s.close()
        except Exception:
            ip_address = "unknown"
        
        return {
            'name': server_name,
            'type': server_type,
            'ip': ip_address
        }
    
    def get_log_filename(self) -> str:
        """Get today's log filename"""
        return datetime.now().strftime("%d%m%Y.log")
    
    def get_log_filepath(self) -> str:
        """Get full path to today's log file"""
        return str(self.log_dir / self.get_log_filename())
    
    def _build_subject(self, job_type: str, status: str) -> str:
        """
        Build email subject line
        
        Format: [server_name] (server_type) - job_type status
        """
        server = self.get_server_info()
        return f"[{server['name']}] ({server['type']}) - {job_type} {status}"
    
    def _build_footer(self) -> str:
        """Build email footer"""
        server = self.get_server_info()
        return f"""
---
Automatic message generated by sipwise-backup
Server: {server['name']} ({server['type']})
IP Address: {server['ip']}
"""
    
    def _send_email(self, subject: str, body: str) -> bool:
        """
        Send email via SMTP
        
        Args:
            subject: Email subject
            body: Email body text
            
        Returns:
            True if sent successfully, False otherwise
        """
        try:
            email_config = self.config.get('email', {})
            smtp_config = email_config.get('smtp', {})
            
            host = smtp_config.get('host')
            port = smtp_config.get('port', 587)
            username = smtp_config.get('username', '')
            password = smtp_config.get('password', '')
            use_tls = smtp_config.get('use_tls', True)
            use_ssl = smtp_config.get('use_ssl', False)
            
            from_addr = email_config.get('from_address', username)
            to_addr = email_config.get('to_address')
            
            if not host or not to_addr:
                print("[EMAIL] SMTP host or recipient not configured")
                return False
            
            # Create message
            msg = MIMEMultipart()
            msg['From'] = from_addr
            msg['To'] = to_addr
            msg['Subject'] = subject
            msg.attach(MIMEText(body, 'plain'))
            
            # Connect and send
            if use_ssl:
                server = smtplib.SMTP_SSL(host, port)
            else:
                server = smtplib.SMTP(host, port)
                if use_tls:
                    server.starttls()
            
            if username and password:
                server.login(username, password)
            
            server.sendmail(from_addr, to_addr, msg.as_string())
            server.quit()
            
            print(f"[EMAIL] Notification sent to {to_addr}")
            return True
            
        except Exception as e:
            print(f"[EMAIL] Failed to send notification: {e}")
            return False
    
    def send_backup_success(self, backup_filename: str, storage_location: str,
                           retention_applied: bool = False, cleanup_applied: bool = False,
                           deleted_count: int = 0) -> bool:
        """
        Send backup success notification
        
        Args:
            backup_filename: Name of the backup file created
            storage_location: Where the backup was saved
            retention_applied: Whether retention policy was applied
            cleanup_applied: Whether cleanup policy was applied
            deleted_count: Number of old backups deleted
        """
        if not self.should_notify('backup_success'):
            return False
        
        subject = self._build_subject("Backup", "SUCCESS")
        server_info = self.get_server_info()
        
        body = f"""BACKUP SUCCESSFUL

Server: {server_info['name']} ({server_info['type']})
Date/Time: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}

Backup Details:
- Backup File: {backup_filename}
- Storage Location: {storage_location}
"""
        
        if retention_applied or cleanup_applied:
            body += "\nMaintenance Applied:\n"
            if retention_applied:
                body += f"- Retention policy applied\n"
            if cleanup_applied:
                body += f"- Cleanup policy applied\n"
            if deleted_count > 0:
                body += f"- {deleted_count} old backup(s) deleted\n"
        
        body += self._build_footer()
        
        return self._send_email(subject, body)
    
    def send_backup_failure(self, error_message: str, stage: str = "unknown") -> bool:
        """
        Send backup failure notification
        
        Args:
            error_message: Description of the error
            stage: Which stage of backup failed (e.g., "MySQL dump", "NGCP config", "storage")
        """
        if not self.should_notify('backup_failure'):
            return False
        
        subject = self._build_subject("Backup", "FAILURE")
        server_info = self.get_server_info()
        
        body = f"""BACKUP FAILED

Server: {server_info['name']} ({server_info['type']})
Date/Time: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}

Error Details:
- Stage: {stage}
- Error: {error_message}

For detailed information, please check the log file:
{self.get_log_filepath()}

Recommended Actions:
1. Check the log file for detailed error information
2. Verify MySQL credentials and connectivity
3. Ensure sufficient disk space
4. Check storage permissions
"""
        
        body += self._build_footer()
        
        return self._send_email(subject, body)
    
    def send_reboot_success(self) -> bool:
        """Send reboot initiation success notification"""
        if not self.should_notify('reboot_success'):
            return False
        
        subject = self._build_subject("Scheduled Reboot", "INITIATED")
        server_info = self.get_server_info()
        
        body = f"""SCHEDULED REBOOT INITIATED

Server: {server_info['name']} ({server_info['type']})
Date/Time: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}

The scheduled system reboot has been initiated.
The server should be back online shortly.

Note: If the server does not come back online within the expected time,
please check the system manually.
"""
        
        body += self._build_footer()
        
        return self._send_email(subject, body)
    
    def send_reboot_failure(self, error_message: str) -> bool:
        """
        Send reboot failure notification
        
        Args:
            error_message: Description of the error
        """
        if not self.should_notify('reboot_failure'):
            return False
        
        subject = self._build_subject("Scheduled Reboot", "FAILURE")
        server_info = self.get_server_info()
        
        body = f"""SCHEDULED REBOOT FAILED

Server: {server_info['name']} ({server_info['type']})
Date/Time: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}

Error Details:
- Error: {error_message}

For detailed information, please check the log file:
{self.get_log_filepath()}

Recommended Actions:
1. Check the log file for detailed error information
2. Verify system permissions
3. Manually reboot the system if required
"""
        
        body += self._build_footer()
        
        return self._send_email(subject, body)
    
    def test_send_email(self) -> bool:
        """
        Send a test email to verify SMTP configuration
        
        Returns:
            True if sent successfully, False otherwise
        """
        if not self.is_enabled():
            print("[EMAIL] Email notifications are disabled in config.yml")
            print("Please set email.enabled to true to test email functionality")
            return False
        
        subject = self._build_subject("Email Test", "SUCCESS")
        server_info = self.get_server_info()
        email_config = self.config.get('email', {})
        smtp_config = email_config.get('smtp', {})
        
        body = f"""EMAIL TEST SUCCESSFUL

This is a test email from sipwise-backup to verify your SMTP configuration.

Server: {server_info['name']} ({server_info['type']})
Date/Time: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}

SMTP Configuration:
- Host: {smtp_config.get('host')}
- Port: {smtp_config.get('port')}
- TLS: {smtp_config.get('use_tls')}
- SSL: {smtp_config.get('use_ssl')}

Recipient: {email_config.get('to_address')}

If you received this email, your SMTP configuration is working correctly!
"""
        
        body += self._build_footer()
        
        return self._send_email(subject, body)


# Convenience functions
_emailer_instance: Optional[EmailNotifier] = None

def get_emailer(config_path: str = "/opt/sipwise-backup/config.yml") -> EmailNotifier:
    """Get or create global EmailNotifier instance"""
    global _emailer_instance
    if _emailer_instance is None:
        _emailer_instance = EmailNotifier(config_path)
    return _emailer_instance

def notify_backup_success(**kwargs) -> bool:
    """Send backup success notification"""
    return get_emailer().send_backup_success(**kwargs)

def notify_backup_failure(**kwargs) -> bool:
    """Send backup failure notification"""
    return get_emailer().send_backup_failure(**kwargs)

def notify_reboot_success() -> bool:
    """Send reboot success notification"""
    return get_emailer().send_reboot_success()

def notify_reboot_failure(**kwargs) -> bool:
    """Send reboot failure notification"""
    return get_emailer().send_reboot_failure(**kwargs)
